CREATE DATABASE MovieCatalogue;
GO

USE MovieCatalogue
GO

CREATE TABLE Genre (
	GenreID INT PRIMARY KEY IDENTITY(1, 1),
	GenreName NVARCHAR (30) NOT NULL
);

CREATE TABLE Director (
	DirectorID INT PRIMARY KEY IDENTITY(1, 1),
	FirstName NVARCHAR (30) NOT NULL,
	LastName NVARCHAR (30) NOT NULL,
	BirthDate DATE NULL
);

CREATE TABLE Rating (
	RatingID INT PRIMARY KEY IDENTITY(1, 1),
	RatingName VARCHAR (5) NOT NULL
);

CREATE TABLE Movie (
	MovieID INT PRIMARY KEY IDENTITY(1, 1),
	GenreID INT FOREIGN KEY REFERENCES Genre(GenreID) NOT NULL,
	DirectorID INT FOREIGN KEY REFERENCES Director(DirectorID) NULL,
	RatingID INT FOREIGN KEY REFERENCES Rating(RatingID) NULL,
	Title NVARCHAR (128) NOT NULL,
	ReleaseDate Date NULL
);

CREATE TABLE Actor (
	ActorID INT PRIMARY KEY IDENTITY(1, 1),
	FirstName NVARCHAR (30) NOT NULL,
	LastName NVARCHAR (30) NOT NULL,
	BirthDate Date NULL
);

CREATE TABLE CastMembers (
	CastMemberID INT PRIMARY KEY IDENTITY(1, 1),
	ActorID INT FOREIGN KEY REFERENCES Actor(ActorID) NOT NULL,
	MovieID INT FOREIGN KEY REFERENCES Movie(MovieID) NOT NULL,
	[Role] NVARCHAR(50) NOT NULL
);